name: abhi191/cw-omnibus
author:
  name: Abhinav
  email: abhinav191@gmail.com
  url: null
copyright: 2015 Abhinav
description: "Source code to omnibus edition of _The Busy Coder's Guide to Android Development_"
